// src/data/pressData.js

// 1. assets 폴더 내의 모든 png 파일을 즉시 가져옵니다.
const imageModules = import.meta.glob("../../../../assets/*.png", {
  eager: true,
});

// 2. 사용할 파일명 목록 (알려주신 이름들)
const pressNames = [
  "그린포스트코리아",
  "낚시춘추",
  "뉴스토마토",
  "뉴스핌",
  "데일리한국",
  "데일리NK",
  "디디넷",
  "디자인정글",
  "디지털투데이",
  "마이데일리",
  "매일노동뉴스",
  "맥스무비",
  "미디어펜",
  "미주한국일보",
  "보안뉴스",
  "비즈한국",
  "산업일보",
  "소비자가만드는신문",
  "스포츠경향",
  "스포츠동아",
  "스포츠월드",
  "스포츠조선",
  "스포츠Q",
  "시사위크",
  "씨네21",
  "아리랑",
  "아시아투데이",
  "약사공론",
  "에너지경제",
  "연합뉴스",
  "위키리크스한국",
  "이뉴스투데이",
  "이로운넷",
  "이코노미조선",
  "이투데이",
  "인민망",
  "일요신문",
  "전기신문",
  "정신의학신문",
  "조이뉴스",
  "철강금속신문",
  "초이스경제",
  "컴퓨터월드",
  "텐아시아",
  "티브이데일리",
  "한국금융",
  "한국대학신문",
  "BBS News",
  "BUSINESS POST",
  "BylineNetwork",
  "CEO스코어데일리",
  "cnbNEWS",
  "DataNews",
  "EBN",
  "ELLE",
  "GameMeca",
  "HUFFPOST",
  "Insight",
  "IT Chosun",
  "IT dongA",
  "JIJI",
  "KBS WORLD",
  "MK스포츠",
  "Newsen",
  "NextDaily",
  "OBS",
  "Pd Journal",
  "ShippingGazette",
  "sportal korea",
  "TBC",
  "TBS",
  "TheKoreaTimes",
  "TheScienceTimes",
];

// 3. 파일명을 매칭하여 데이터 배열 생성
export const pressList = pressNames.map((name, i) => {
  const path = `../../../../assets/${name}.png`;
  return {
    id: i,
    logo: imageModules[path]?.default || imageModules[path], // Vite 버전에 따른 처리
    name: name,
  };
});
