export const NEWS_NAMES = [
  { name: '008 1', src: './images/light_mode_logo/008 1.png' },
  { name: '032 1', src: './images/light_mode_logo/032 1.png' },
  { name: '930 2', src: './images/light_mode_logo/930 2.png' },
  { name: 'asset 0 1', src: './images/light_mode_logo/asset 0 1.png' },
  { name: 'asset 1 1', src: './images/light_mode_logo/asset 1 1.png' },
  { name: 'asset 2 1', src: './images/light_mode_logo/asset 2 1.png' },
  { name: 'asset 4 1', src: './images/light_mode_logo/asset 4 1.png' },
  { name: 'asset 5 1', src: './images/light_mode_logo/asset 5 1.png' },
  { name: 'asset 6 1', src: './images/light_mode_logo/asset 6 1.png' },
  { name: 'asset 7 1', src: './images/light_mode_logo/asset 7 1.png' },
  { name: 'asset 8 1', src: './images/light_mode_logo/asset 8 1.png' },
  { name: 'asset 9 1', src: './images/light_mode_logo/asset 9 1.png' },
  { name: 'asset 10', src: './images/light_mode_logo/asset 10.png' },
  { name: 'asset 11 1', src: './images/light_mode_logo/asset 11 1.png' },
  { name: 'asset 12 1', src: './images/light_mode_logo/asset 12 1.png' },
  { name: 'asset 13 1', src: './images/light_mode_logo/asset 13 1.png' },
  { name: 'asset 14 1', src: './images/light_mode_logo/asset 14 1.png' },
  { name: 'asset 15 1', src: './images/light_mode_logo/asset 15 1.png' },
  { name: 'asset 16 1', src: './images/light_mode_logo/asset 16 1.png' },
  { name: 'asset 17 1', src: './images/light_mode_logo/asset 17 1.png' },
  { name: 'asset 19 1', src: './images/light_mode_logo/asset 19 1.png' },
  { name: 'asset 20 1', src: './images/light_mode_logo/asset 20 1.png' },
  { name: 'asset 21 1', src: './images/light_mode_logo/asset 21 1.png' },
  { name: 'asset 22 1', src: './images/light_mode_logo/asset 22 1.png' },
  { name: 'asset 23 1', src: './images/light_mode_logo/asset 23 1.png' },
  { name: 'asset 24 1', src: './images/light_mode_logo/asset 24 1.png' },
  { name: 'asset 25 1', src: './images/light_mode_logo/asset 25 1.png' },
  { name: 'asset 27 1', src: './images/light_mode_logo/asset 27 1.png' },
  { name: 'asset 28 1', src: './images/light_mode_logo/asset 28 1.png' },
  { name: 'asset 29 1', src: './images/light_mode_logo/asset 29 1.png' },
  { name: 'asset 31 1', src: './images/light_mode_logo/asset 31 1.png' },
  { name: 'asset 32 1', src: './images/light_mode_logo/asset 32 1.png' },
  { name: 'asset 34 1', src: './images/light_mode_logo/asset 34 1.png' },
  { name: 'asset 35 1', src: './images/light_mode_logo/asset 35 1.png' },
  { name: 'asset 36 1', src: './images/light_mode_logo/asset 36 1.png' },
  { name: 'asset 37 1', src: './images/light_mode_logo/asset 37 1.png' },
  { name: 'asset 38 1', src: './images/light_mode_logo/asset 38 1.png' },
  { name: 'asset 39 1', src: './images/light_mode_logo/asset 39 1.png' },
  { name: 'asset 40 1', src: './images/light_mode_logo/asset 40 1.png' },
  { name: 'asset 41 1', src: './images/light_mode_logo/asset 41 1.png' },
  { name: 'asset 42 1', src: './images/light_mode_logo/asset 42 1.png' },
  { name: 'asset 43 1', src: './images/light_mode_logo/asset 43 1.png' },
  { name: 'asset 44 1', src: './images/light_mode_logo/asset 44 1.png' },
  { name: 'asset 45 1', src: './images/light_mode_logo/asset 45 1.png' },
  { name: 'asset 46 1', src: './images/light_mode_logo/asset 46 1.png' },
  { name: 'asset 47 1', src: './images/light_mode_logo/asset 47 1.png' },
  { name: 'asset 48 1', src: './images/light_mode_logo/asset 48 1.png' },
  { name: 'asset 49 1', src: './images/light_mode_logo/asset 49 1.png' },
  { name: 'asset 50 1', src: './images/light_mode_logo/asset 50 1.png' },
  { name: 'asset 51 1', src: './images/light_mode_logo/asset 51 1.png' },
  { name: 'asset 52 1', src: './images/light_mode_logo/asset 52 1.png' },
  { name: 'asset 53 1', src: './images/light_mode_logo/asset 53 1.png' },
  { name: 'asset 54 1', src: './images/light_mode_logo/asset 54 1.png' },
  { name: 'asset 55 1', src: './images/light_mode_logo/asset 55 1.png' },
  { name: 'asset 56 1', src: './images/light_mode_logo/asset 56 1.png' },
  { name: 'asset 57 1', src: './images/light_mode_logo/asset 57 1.png' },
  { name: 'asset 58 1', src: './images/light_mode_logo/asset 58 1.png' },
  { name: 'asset 59 1', src: './images/light_mode_logo/asset 59 1.png' },
  { name: 'asset 60 1', src: './images/light_mode_logo/asset 60 1.png' },
  { name: 'asset 61 1', src: './images/light_mode_logo/asset 61 1.png' },
  { name: 'asset 62 1', src: './images/light_mode_logo/asset 62 1.png' },
  { name: 'asset 63 1', src: './images/light_mode_logo/asset 63 1.png' },
  { name: 'asset 64 1', src: './images/light_mode_logo/asset 64 1.png' },
  { name: 'asset 65 1', src: './images/light_mode_logo/asset 65 1.png' },
  { name: 'asset 66 1', src: './images/light_mode_logo/asset 66 1.png' },
  { name: 'asset 67 1', src: './images/light_mode_logo/asset 67 1.png' },
  { name: 'asset 68 1', src: './images/light_mode_logo/asset 68 1.png' },
  { name: 'asset 69 1', src: './images/light_mode_logo/asset 69 1.png' },
  { name: 'asset 70 1', src: './images/light_mode_logo/asset 70 1.png' },
  { name: 'asset 71 1', src: './images/light_mode_logo/asset 71 1.png' },
  { name: 'asset 72 1', src: './images/light_mode_logo/asset 72 1.png' },
  { name: 'asset 73 1', src: './images/light_mode_logo/asset 73 1.png' },
  { name: 'asset 74 1', src: './images/light_mode_logo/asset 74 1.png' },
  { name: 'asset 75 1', src: './images/light_mode_logo/asset 75 1.png' },
  { name: 'asset 76 1', src: './images/light_mode_logo/asset 76 1.png' },
  { name: 'asset 77 1', src: './images/light_mode_logo/asset 77 1.png' },
  { name: 'asset 78 1', src: './images/light_mode_logo/asset 78 1.png' },
  { name: 'asset 79 1', src: './images/light_mode_logo/asset 79 1.png' },
  { name: 'asset 80 1', src: './images/light_mode_logo/asset 80 1.png' },
  { name: 'asset 81 1', src: './images/light_mode_logo/asset 81 1.png' },
  { name: 'asset 82 1', src: './images/light_mode_logo/asset 82 1.png' },
  { name: 'asset 83 1', src: './images/light_mode_logo/asset 83 1.png' },
  { name: 'asset 84 1', src: './images/light_mode_logo/asset 84 1.png' },
  { name: 'asset 85 1', src: './images/light_mode_logo/asset 85 1.png' },
  { name: 'asset 86 1', src: './images/light_mode_logo/asset 86 1.png' },
  { name: 'asset 87 1', src: './images/light_mode_logo/asset 87 1.png' },
  { name: 'asset 88 1', src: './images/light_mode_logo/asset 88 1.png' },
  { name: 'asset 89 1', src: './images/light_mode_logo/asset 89 1.png' },
  { name: 'asset 90 1', src: './images/light_mode_logo/asset 90 1.png' },
  { name: 'asset 92 1', src: './images/light_mode_logo/asset 92 1.png' },
  { name: 'asset 93 1', src: './images/light_mode_logo/asset 93 1.png' },
  { name: 'asset 94 1', src: './images/light_mode_logo/asset 94 1.png' },
  { name: 'asset 95 1', src: './images/light_mode_logo/asset 95 1.png' },
  {
    name: 'nsd132851977 1',
    src: './images/light_mode_logo/nsd132851977 1.png',
  },
  {
    name: 'nsd165811867 1',
    src: './images/light_mode_logo/nsd165811867 1.png',
  },
  {
    name: 'nsd181452869 1',
    src: './images/light_mode_logo/nsd181452869 1.png',
  },
];

export const ROLLING_NEWS = {
  left: [
    {
      name: '연합뉴스',
      title: '[속보] 도심 공원 ‘조용한 독서존’ 시범 운영… 시민 호응 이어져',
    },
    {
      name: 'YTN',
      title: '내년 최저임금 협상 극적 타결, 노사 양측 "아쉽지만 수용"',
    },
    {
      name: 'KBS News',
      title: '국내 연구진, 차세대 친환경 수소 생산 기술 개발 성공',
    },
    {
      name: '매일경제',
      title: '코스피, 외국인 매수세에 2% 급등… 반도체주 강세',
    },
    {
      name: 'SBS',
      title: '주말 전국 맑고 포근한 날씨… 나들이객으로 붐비는 고속도로',
    },
  ],

  right: [
    {
      name: '서울경제',
      title: '여섯 번째 착한 소비 캠페인, 지역 상권 회복에 긍정적 영향.',
    },
    {
      name: '한국경제',
      title: 'MZ세대 사로잡은 ‘레트로 간식’ 열풍, 편의점 매출 견인',
    },
    {
      name: 'JTBC',
      title: '서울시, 심야 자율주행 택시 운행 지역 강남권으로 확대',
    },
    {
      name: '스포츠조선',
      title: '손흥민, 시즌 10호골 폭발… 현지 언론 "월드클래스의 품격"',
    },
    {
      name: '전자신문',
      title: 'AI 기술 도입한 가전제품 인기, 스마트홈 시장 가파른 성장세',
    },
  ],
};
